export const expenses = [{
  "exp_id":1,
  "exp_name":"tea",
  "exp_value":20,
  "date":"17/03/2019",
  "exp_category":""
},
{
  "exp_id":2,
  "exp_name":"juice",
  "exp_value":50,
  "exp_date":"17/03/2019",
  "exp_category":""
},
{
  "exp_id":3,
  "exp_name":"food",
  "exp_value":50,
  "date":"17/03/2019",
  "exp_category":""
}]